on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-nm-babel-workflow.yml
    - scripts/e2e-setup-ci.sh
    - packages/yarnpkg-nm/sources/hoist.ts
    - packages/yarnpkg-nm/sources/buildNodeModulesTree.ts
    - packages/plugin-nm/sources/NodeModulesLinker.ts
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-nm-babel-workflow.yml
    - scripts/e2e-setup-ci.sh
    - packages/yarnpkg-nm/sources/hoist.ts
    - packages/yarnpkg-nm/sources/buildNodeModulesTree.ts
    - packages/plugin-nm/sources/NodeModulesLinker.ts

name: 'E2E NM Babel Install'
jobs:
  chore:
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - windows-latest

    name: 'Validating Babel install via node-modules linker on ${{matrix.platform}}'
    runs-on: ${{matrix.platform}}

    steps:
    - name: Enable git longpaths
      run: git config --global core.longpaths true

    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running node_modules install with self-validation'
      run: |
        source scripts/e2e-setup-ci.sh nm
        git clone https://github.com/babel/babel.git
        cd babel
        yarn config unset yarnPath
        NM_DEBUG_LEVEL=1 yarn
      shell: bash
