on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-next-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Next'
jobs:
  chore:
    name: 'Validating Next.js'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test, without TypeScript'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn init

        # Required
        yarn add next@canary react react-dom

        # Test itself
        yarn add raw-loader

        mkdir pages
        echo 'import text from "raw-loader!./text.txt"; export default () => <div>{text}</div>;' | tee pages/index.js
        echo 'hello world!' | tee pages/text.txt

        yarn next build

    - name: 'Running the integration test, with TypeScript'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn init

        # Required
        yarn add typescript next@canary react react-dom @types/react @types/react-dom @types/node

        # Test itself
        yarn add raw-loader

        mkdir pages
        echo 'const text = require("raw-loader!./text.txt").default; export default () => <div>{text}</div>;' | tee pages/home.tsx
        echo 'hello world!' | tee pages/text.txt

        yarn next build
      if: |
        success() || failure()
