#
on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-storybook-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Storybook'
jobs:
  chore:
    name: 'Validating Storybook (with a React app)'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Install Node'
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-react-app my-cra && cd my-cra
        yarn dlx -p @storybook/cli@next sb init --yes
        yarn build-storybook

