# test

on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-snowpack-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Snowpack'
jobs:
  chore:
    name: 'Validating Snowpack'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-snowpack-app my-csa --template @snowpack/app-template-react --use-yarn
        cd my-csa && yarn build

    - name: 'Running the TypeScript integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-snowpack-app my-csa-ts --template @snowpack/app-template-react-typescript --use-yarn
        cd my-csa-ts
        # Snowpack executes `yarn pnpify tsc`
        cat package.json | jq '.scripts.pnpify="tsc"' | tee package.json
        yarn build
      if: |
        always()
