#
on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-storybook-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Storybook'
env:
  STORYBOOK_DISABLE_TELEMETRY: 1
jobs:
  chore:
    name: 'Validating Storybook (with a React app)'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-react-app my-cra && cd my-cra

        # TODO: Remove when create-react-app fixes their ESLint setup
        yarn add -D eslint-config-react-app eslint

        yarn dlx -p @storybook/cli@next sb init --yes
        yarn build-storybook

