on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-svelte-kit-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E SvelteKit'
jobs:
  chore:
    name: 'Validating SvelteKit'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Install Node'
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yes | yarn create svelte@next my-app && cd my-app
        yarn
        yarn build

