on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-mocha-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Mocha'
jobs:
  chore:
    name: 'Validating Mocha'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn init -p
        yarn add mocha
        mkdir test

        echo "const assert = require('assert'); it('should pass', function() { assert.equal(true, true); });" | tee pass.test.js
        yarn mocha pass.test.js

        echo "const assert = require('assert'); it('should fail', function() { assert.equal(true, false); });" | tee fail.test.js
        ! yarn mocha fail.test.js

        yarn add left-pad

        echo "const assert = require('assert'); const leftPad = require('left-pad'); it('should resolve a module', () => { assert.equal(typeof leftPad, 'function');});" | tee module.test.js
        yarn mocha module.test.js
