on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-cra-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E CRA'
jobs:
  chore:
    name: 'Validating Create-React-App'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        yarn dlx create-react-app my-cra && cd my-cra
        yarn build
