on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-prettier-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Prettier'
jobs:
  chore:
    name: 'Validating Prettier'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn init -p
        yarn add prettier

        echo 'semi: true' > .prettierrc

        echo '42;' | tee ok.js
        yarn prettier --check ok.js

        echo '42' | tee ko.js
        ! yarn prettier --check ko.js
