on: [issues]

name: 'Sherlock for Yarn'
jobs:
  issue:
    name: 'Running Sherlock'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: 'Build the standard bundle & plugins'
      run: |
        set -e
        node --version
        node ./scripts/run-yarn.js build:cli
        node ./scripts/run-yarn.js build:plugin-exec
        node ./scripts/run-yarn.js build:plugin-stage
        node ./scripts/run-yarn.js build:plugin-typescript
        node ./scripts/run-yarn.js build:plugin-version
        node ./scripts/run-yarn.js build:plugin-workspace-tools

    - name: 'Sherlock Payload'
      uses: ./scripts/actions/local-yarn-command
      with:
        args: 'sherlock payload'

    - name: 'Sherlock Execution'
      uses: ./scripts/actions/local-yarn-command
      with:
        args: 'sherlock exec'

    - name: 'Sherlock Reporting'
      uses: ./scripts/actions/local-yarn-command
      with:
        args: 'sherlock report'
      env:
        GITHUB_TOKEN: ${{secrets.YARNBOT_TOKEN}}
