on: [issues]

name: 'Sherlock for Yarn'
jobs:
  issue:
    name: 'Running Sherlock'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Install Node'
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: 'Always use the latest sherlock'
      run: |
        node ./scripts/run-yarn.js add @arcanis/sherlock
      shell: bash

    - name: 'Sherlock Payload'
      id: sherlock-payload
      uses: ./scripts/actions/local-yarn-command
      with:
        args: 'sherlock payload'

    - name: 'Sherlock Execution'
      if: ${{steps.sherlock-payload.sherlock-outcome == 'success'}}
      uses: ./scripts/actions/local-yarn-command
      with:
        args: 'sherlock exec'

    - name: 'Sherlock Reporting'
      if: ${{steps.sherlock-payload.sherlock-outcome == 'success'}}
      uses: ./scripts/actions/local-yarn-command
      with:
        args: 'sherlock report'
      env:
        GITHUB_TOKEN: ${{secrets.YARNBOT_TOKEN}}
